name: "Update Workflow Status"
description: "Updates an existing Slack message with GitHub Actions workflow status and metadata using Slack's Block Kit"

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID where the original message was posted"
    required: true
  thread_ts:
    description: "Timestamp of the message to update"
    required: true
  status:
    description: "Updated status of the deployment"
    required: true
  env:
    description: "Environment name (e.g. qa, prod)"
    required: false
    default: "unknown"
  tag:
    description: "Tag or version of the deployment"
    required: false
    default: "unknown"
  text:
    description: "Fallback plain text for the message"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Get emoji based on updated status
      id: emoji
      shell: bash
      run: |
        case "${{ inputs.status }}" in
          success) echo "emoji=:white_check_mark:" >> "$GITHUB_OUTPUT" ;;
          failed)  echo "emoji=:x:" >> "$GITHUB_OUTPUT" ;;
          ongoing) echo "emoji=:arrows_counterclockwise:" >> "$GITHUB_OUTPUT" ;;
          *)
            echo "Error: Unknown status '${{ inputs.status }}'. Expected one of: success, failed, ongoing."
            exit 1
            ;;
        esac

    - name: Update workflow status
      uses: slackapi/slack-github-action@v2.1.1
      with:
        errors: 'true'
        method: chat.update
        token: ${{ inputs.token }}
        payload: |
          channel: ${{ inputs.channel }}
          ts: ${{ inputs.thread_ts }}
          text: ${{ inputs.text }}
          blocks:
            - type: header
              text:
                type: plain_text
                text: "${{ steps.emoji.outputs.emoji }} ${{ github.workflow }} #${{ github.run_number }}"
                emoji: true
            - type: context
              elements:
                - type: mrkdwn
                  text: "*Repository:* `${{ github.repository }}` • *Branch:* `${{ github.ref_name }}` • *Run by:* `@${{ github.actor }}`"
            - type: divider
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Status*\n${{ inputs.status }}"
                - type: mrkdwn
                  text: "*Duration*\nTBT"
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Environment*\n${{ inputs.env }}"
                - type: mrkdwn
                  text: "*Tag*\n${{ inputs.tag }}"
            - type: divider
            - type: section
              fields:
                - type: mrkdwn
                  text: ":copyright: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
                - type: mrkdwn
                  text: ":page_facing_up: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>"
