name: "Update Slack Message"
description: "Updates a Slack message using Slack's Block Kit"

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  text:
    description: "Plain text for the message (markdown is supported)"
    required: true
  ts:
    description: "Timestamp of the Slack message to update (used when modifying an existing message)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Slack message
      id: send_slack_message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.update
        token: ${{ inputs.token }}
        payload: |
          channel: ${{ inputs.channel }}
          text: ${{ inputs.text }}
          ts: ${{ inputs.ts }}
