name: "Send Slack Message"
description: "Sends a Slack message using Slack's Block Kit and outputs the message timestamp (ts)."

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  text:
    description: "Plain text for the message (markdown is supported)"
    required: false
    default: "${{ github.workflow }} #${{ github.run_number }}" # The `text` is used in places where the content cannot be rendered when using blocks
  thread_ts:
    description: "Timestamp of the message to post in a thread"
    required: false
    default: ""
  blocks:
    description: "JSON array string for Slack Block Kit layout (optional)"
    required: false
    default: ""

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_slack_message.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Validate input
      shell: bash
      run: |
        echo "${{ inputs.blocks }}" > blocks_input.json
        
        BLOCKS_INPUT=$(cat blocks_input.json)
        
        if [[ -z "${{ inputs.text }}" && -z "$BLOCKS_INPUT" ]]; then
          echo "Error: You must provide at least one of 'text' or 'blocks'."
          exit 1
        fi

    - name: Write Slack payload to file
      shell: bash
      run: |
        echo "channel: ${{ inputs.channel }}" > payload.yml
        if [[ -n "${{ inputs.text }}" ]]; then
          echo "text: ${{ inputs.text }}" >> payload.yml
        fi
        echo "thread_ts: \"${{ inputs.thread_ts }}\"" >> payload.yml

        # Add blocks only if not empty
        if [[ -s blocks_input.json && $(jq -e 'length > 0' blocks_input.json) ]]; then
          echo "blocks: $(cat blocks_input.json)" >> payload.yml
        fi

    - name: Send Slack message
      id: send
      uses: slackapi/slack-github-action@v2.1.1
      with:
        token: ${{ inputs.token }}
        method: chat.postMessage
        payload-file-path: payload.yml