name: "Send Slack Message"
description: "Sends a Slack message using Slack's Block Kit and outputs the message timestamp (ts)."

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  text:
    description: "Plain text for the message (markdown is supported)"
    required: false
    default: "${{ github.workflow }} #${{ github.run_number }}" # The `text` is used in places where the content cannot be rendered when using blocks
  thread_ts:
    description: "Timestamp of the message to post in a thread"
    required: false
    default: ""
  env:
    description: "Environment name (e.g. qa, prod)"
    required: false
    default: ""
  tag:
    description: "Tag or version of the deployment"
    required: false
    default: ""

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_slack_message.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Render Slack blocks template
      shell: bash
      run: |
        cp "${{ github.action_path }}/blocks-template.json" blocks.json
        
        sed -i "s|{{ env }}|${{ inputs.env }}|g" blocks.json
        sed -i "s|{{ tag }}|${{ inputs.tag }}|g" blocks.json

    - name: Write Slack payload to file
      shell: bash
      run: |
        echo "channel: ${{ inputs.channel }}" > payload.yml
        echo "text: '${{ github.workflow }} #${{ github.run_number }}'" >> payload.yml
        echo "thread_ts: \"${{ inputs.thread_ts }}\"" >> payload.yml
        echo "blocks: $(cat blocks.json)" >> payload.yml

    - name: Send Slack message
      id: send
      uses: slackapi/slack-github-action@v2.1.1
      with:
        token: ${{ inputs.token }}
        method: chat.postMessage
        payload-file-path: payload.yml
        payload-templated: 'true'