name: "Send Slack Message"
description: "Sends a Slack message using Slack's Block Kit and outputs the message timestamp (ts)."

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  text:
    description: "Fallback plain text for the message"
    required: true
  thread_ts:
    description: "Timestamp of the parent message for threaded replies"
    required: false
    default: ""

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_slack_message.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Send Slack message
      id: send_slack_message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: |
          channel: ${{ inputs.channel }}
          text: ${{ inputs.text }}
          thread_ts: "${{ inputs.thread_ts }}"
          
