name: "Docker Build and Push (Demo Set)"
description: "Simulates running docker build and push using two actions"
runs:
  using: "composite"
  steps:
    - name: Build step
      uses: ./actions/docker/build
      with:
        aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
        aws_region: ${{ env.AWS_REGION }}

    - name: Push step
      uses: ./actions/docker/push
      with:
        aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
        aws_region: ${{ env.AWS_REGION }}
