name: "Override input"
description: "Simulates a input override"
inputs:
  override_input:
    description: "Override input"
    default: ${{ env.OVERRIDE_INPUT }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Echo override input
      shell: bash
      run: echo "The value of the input is - ${{ inputs.override_input }}"