name: "Sync and Wait (Demo Set)"
description: "Simulates sync and wait commands in argocd"
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: ./actions/aws/configure-creds
      with:
        aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
        aws_region: ${{ env.AWS_REGION }}
    - name: Sync step
      uses: ./actions/argocd/sync
      with:
        service_name: ${{ env.SERVICE_NAME }}
    - name: Wait step
      uses: ./actions/argocd/wait
      with:
        service_name: ${{ env.SERVICE_NAME }}
