name: "Sync and Wait (Demo Set)"
description: "Simulates sync and wait commands in argocd"
inputs:
  timeout_seconds:
    description: "The maximum time to wait for the deployment to complete"
    required: false
    default: "300"  # Default to 5 minutes if not specified
runs:
  using: "composite"
  steps:
    - name: Verify ArgoCD Username
      shell: bash
      run: |
        if [ -z "${{ inputs.argocd_username }}" ]; then
          echo "Error: ArgoCD username is required."
          exit 1
        else
            echo "✅ ArgoCD username is set to '${{ env.ARGOCD_USERNAME }}'."
        fi
    - name: Configure AWS Credentials
      uses: ./actions/aws/configure-creds
      with:
        aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
        aws_region: ${{ env.AWS_REGION }}
    - name: Sync step
      uses: ./actions/argocd/sync
      with:
        service_name: ${{ env.SERVICE_NAME }}
    - name: Wait step
      uses: ./actions/argocd/wait
      with:
        service_name: ${{ env.SERVICE_NAME }}
        timeout_seconds: ${{ inputs.timeout_seconds }}
