name: "ArgoCD Sync"
description: "Actions to simulate ArgoCD sync"
inputs:
  service_name:
    description: "The name of the cluster to sync and wait"
    required: true
runs:
  using: "composite"
  steps:
    - name: ArgoCD Sync
      shell: bash
      run: echo "🔄 Simulating ArgoCD sync for cluster ${{ inputs.service_name }}"