name: "Validate Multiple Inputs"
description: "Fails if any given input (via env) is empty; reports all missing inputs"

runs:
  using: "composite"
  steps:
    - name: Validate inputs via env
      shell: bash
      env:
        INPUTS: ${{ env.INPUTS }}
      run: |
        set -euo pipefail

        MISSING=()
        for pair in $INPUTS; do
          name="${pair%%=*}"
          value="${pair#*=}"
          if [[ -z "$value" ]]; then
            MISSING+=("$name")
            echo "❌ Error: Input '$name' is required and cannot be empty"
          else
            echo "✅ Info: Input '$name' is valid"
          fi
        done

        if [[ ${#MISSING[@]} -gt 0 ]]; then
          echo "❌ Error: The following inputs are missing or empty: ${MISSING[*]}"
          exit 1
        fi
