name: "Validate Multiple Inputs"
description: "Fails if any input (via list input) is empty; reports all missing"

inputs:
  list_of_inputs:
    description: "Multiline list of 'name=value' pairs"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs via list_of_inputs
      shell: bash
      run: |
        set -euo pipefail

        MISSING=()
        while IFS= read -r pair; do
          name="${pair%%=*}"
          value="${pair#*=}"
          if [[ -z "$value" ]]; then
            MISSING+=("$name")
            echo "❌ Error: Input '$name' is required and cannot be empty"
          else
            echo "✅ Info: Input '$name' is valid"
          fi
        done <<< "${{ inputs.list_of_inputs }}"

        if (( ${#MISSING[@]} )); then
          echo "❌ Error: The following inputs are missing or empty: ${MISSING[*]}"
          exit 1
        fi
