---
name: "Create Release"
description: "Creates a GitHub release with the specified tag and body content"

inputs:
  body:
    description: "Body for the release"
    required: true
  github_token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}
  tag:
    description: "The tag name to push (e.g., v1.2.3, 4.5.6)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.18.0
      with:
        makeLatest: true
        tag: ${{ inputs.tag }}
        body: ${{ inputs.body }}
        token: ${{ inputs.github_token }}
