name: "Send Deployment Status Message"
description: "Sends a Slack message with deployment status and metadata using GitHub Actions and Slack Block Kit"

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  emoji:
    description: "Slack emoji that represents the workflow status (e.g. :white_check_mark: for success, :x: for failure, :arrows_counterclockwise: for ongoing)"
    required: true
  env:
    description: "Environment name (e.g. qa, prod)"
    required: true
  tag:
    description: "Tag or version of the deployment"
    required: true
  thread_ts:
    description: "Timestamp of the parent Slack message to reply to (used for sending a message in a thread)"
    required: false
    default: ""

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_deployment_status.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Send deployment status message
      id: send_deployment_status
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload-file-path: ${{ github.action_path }}/../payloads/deployment-status.json
        payload-templated: 'true'
      env:
        ACTOR: ${{ github.actor }}
        REF_NAME: ${{ github.ref_name }}
        REPOSITORY: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        RUN_NUMBER: ${{ github.run_number }}
        SHA: ${{ github.sha }}
        WORKFLOW: ${{ github.workflow }}
        CHANNEL: ${{ inputs.channel }}
        EMOJI: ${{ inputs.emoji }}
        ENVIRONMENT: ${{ inputs.env }}
        TAG: ${{ inputs.tag }}
        THREAD_TS: ${{ inputs.thread_ts }}
