name: "Send Slack Message"
description: "Sends a Slack message using Slack's Block Kit and outputs the message timestamp (ts)."

inputs:
  text:
    description: "Plain text for the message (markdown is supported)"
    required: true
  thread_ts:
    description: "Timestamp of the parent Slack message to reply to (used for sending a message in a thread)"
    required: false
    default: ""

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_slack_message.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Send Slack message
      id: send_slack_message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ env.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ env.SLACK_CHANNEL_ID }}
          text: "${{ inputs.text }}"
          thread_ts: "${{ inputs.thread_ts }}"
