name: "Configure AWS Credentials"
description: "Simulates a step to configure AWS credentials"
runs:
  using: "composite"
  steps:
    - name: Echo push
      shell: bash
      run: echo "📤 Simulating AWS credentials configuration..."