name: "Send Slack Message"
description: "Sends a raw Slack JSON payload directly"

inputs:
  token:
    required: true
    description: "Slack Bot Token"
  payload:
    required: true
    description: "Raw Slack JSON payload string"

runs:
  using: "composite"
  steps:
    - name: Decode and Send
      run: |
        echo "${{ steps.slack_payload.outputs.payload }}" | base64 -d > /tmp/slack-payload.json
      shell: bash

    - name: Send Slack message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        payload-file-path: /tmp/slack-payload.json
        token: ${{ inputs.slack_token }}
