name: "Send Slack Message"
description: "Sends a Slack message using Slack's Block Kit and outputs the message timestamp (ts)."

inputs:
  token:
    description: "Slack Bot OAuth token with `chat:write` permission"
    required: true
  channel:
    description: "Slack channel ID to post to"
    required: true
  text:
    description: "Fallback plain text for the message"
    required: false
    default: ""
  thread_ts:
    description: "Timestamp of the parent message for threaded replies"
    required: false
    default: ""
  env:
    description: "Environment name (e.g. qa, prod)"
    required: true
  tag:
    description: "Tag or version of the deployment"
    required: true

outputs:
  ts:
    description: "Timestamp of the posted Slack message"
    value: "${{ steps.send_slack_message.outputs.ts }}"

runs:
  using: "composite"
  steps:
    - name: Send Slack message
      id: send_slack_message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: |
          channel: ${{ inputs.channel }}
          text: ${{ inputs.text }}
          thread_ts: "${{ inputs.thread_ts }}"
          blocks:
            - type: header
              text:
                type: plain_text
                text: ":arrows_counterclockwise: ${{ github.workflow }}"
                emoji: true
            - type: context
              elements:
                - type: mrkdwn
                  text: "*Repository:* `${{ github.repository }}`"
            - type: divider
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Environment*\n${{ inputs.env }}"
                - type: mrkdwn
                  text: "*Tag*\n${{ inputs.tag }}"
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Status*\n${{ job.status }}"
                - type: mrkdwn
                  text: "*Triggered by*\n@${{ github.actor }}"
            - type: section
              fields:
                - type: mrkdwn
                  text: ":copyright: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
                - type: mrkdwn
                  text: "::page_facing_up:: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>"
            - type: divider
            - type: context
              elements:
                - type: mrkdwn
                  text: "Need help? Ask in `/ask-devops-il` :robot_face:"
