name: "Docker Build and Push (Demo Set)"
description: "Simulates running docker build and push using two actions"
runs:
  using: "composite"
  steps:
    - name: Echo ENVAR BAR
      run: echo "BAR is ${{ vars.BAR }}"
      shell: bash

    - name: Echo ENVAR FOO
      run: echo "FOO is ${{ secrets.FOO }}"
      shell: bash

#    - name: Build step
#      uses: ./actions/docker/build
#
#    - name: Push step
#      uses: ./actions/docker/push
