name: "Docker Build and Push (Demo Set)"
description: "Simulates running docker build and push using a file"
runs:
  using: "composite"
  steps:
    - name: Load and print env values
      shell: bash
      run: |
        if [[ ! -f config.env ]]; then
          echo "Missing config.env file!"
          exit 1
        fi

        echo "Contents of config.env:"
        cat config.env

        echo "Sourcing config.env..."
        set -o allexport
        source config.env
        set +o allexport

        echo "BAR is: $BAR"
        echo "FOO is: $FOO"

    - name: check foo
      shell: bash
      run: |
   
        if [[ "$FOO" == "foo" ]]; then
          echo "FOO is set to the expected secret value."
        else
          echo "FOO does not match the expected secret value."
        fi

    - name: check FOO
      shell: bash
      run: |
        if [[ "$FOO" == "FOO" ]]; then
          echo "FOO is set to the expected secret value."
        else
          echo "FOO does not match the expected secret value."
        fi