name: "Reusable CI/CD for Environment"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
jobs:
  cd:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      SERVICE_NAME: "service_foo"
      IMAGE_TAG: ${{ inputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Sync and wait for ArgoCD
        uses: ./action-sets/argocd/sync-and-wait-2
      - name: Notify ArgoCD sync completion
        run: |
          echo "ArgoCD sync completed for service: ${{ env.SERVICE_NAME }} with image tag: ${{ env.IMAGE_TAG }}"
