name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yaml

  use-outputs:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - name: Print outputs from reusable workflow
        run: |
          echo "foo: ${{ needs.call-reusable.outputs.foo }}"
          echo "bar: ${{ needs.call-reusable.outputs.bar }}"

  call-reusable-2:
    uses: ./.github/workflows/reusable.yaml

  use-outputs-2:
    runs-on: ubuntu-latest
    needs: call-reusable-2
    steps:
      - name: Print outputs from reusable workflow
        run: |
          echo "foo: ${{ needs.call-reusable.outputs.foo }}"
          echo "bar: ${{ needs.call-reusable.outputs.bar }}"