name: CI
on: [push]
jobs:
  run-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: ./actions/aws/configure-creds

      - name: Echo from docker/build
        uses: ./actions/docker/build

      - name: "Echo from action-set: docker-build-push"
        uses: ./templates/action-sets/docker-build-push

  run-template-ci:
    uses: .github/workflows/template_ci.yaml@main