name: CI
on: [push]
jobs:
  run-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: ./actions/aws/configure-creds

      - name: Build
        uses: ./actions/docker/build

      - name: Push
        uses: ./actions/docker/push

      - name: Build and Push Docker Image
        uses: ./action-sets/docker/build-and-push

  run-reusable-ci:
    needs: [run-echo]
    uses: ./.github/workflows/reusable-ci.yaml