name: CI
on: [push]

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: main  # grants access to environment vars/secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write env and secret values to file
        run: |
          echo "BAR=${{ vars.BAR }}" >> config.env
          echo "FOO=${{ secrets.FOO }}" >> config.env
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> config.env
          echo "SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" >> config.env
          
          if [[ -f config.env ]]; then
            while read -r line; do
              echo "$line" >> "$GITHUB_ENV"
            done < config.env
          else
            echo "config.env not found!"
            exit 1
          fi
        shell: bash

      - name: Use composite action to read and print values
        uses: ./action-sets/docker-2/build-and-push


      - id: send
        continue-on-error: true
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: "${{ env.SLACK_BOT_TOKEN }}"
          payload: >
            {
              "channel": "${{ env.SLACK_CHANNEL_ID}}",
              "text": "FOO FOO",
            }

#  run-all-actions:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Configure AWS Credentials
#        uses: ./actions/aws/configure-creds
#
#      - name: Build
#        uses: ./actions/docker/build
#
#      - name: Push
#        uses: ./actions/docker/push
#
#      - name: Sync ArgoCD
#        uses: ./actions/argocd/sync
#
#      - name: Wait for ArgoCD
#        uses: ./actions/argocd/wait
#
#      - name: Sync ArgoCD
#        uses: ./action-sets/argocd/sync-and-wait
#
#      - name: Build and Push Docker Image
#        uses: ./action-sets/docker/build-and-push
#
#  run-only-action-sets:
#    needs: run-all-actions
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Build and Push Docker Image
#        uses: ./action-sets/docker/build-and-push
#
#      - name: Sync ArgoCD
#        uses: ./action-sets/argocd/sync-and-wait
#
#  run-only-reusable-ci:
#    needs: run-only-action-sets
#    uses: ./.github/workflows/reusable-ci.yaml
#
#  run-only-reusable-cd:
#    needs: run-only-reusable-ci
#    uses: ./.github/workflows/reusable-cd.yaml