name: Release
run-name: Release - ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
        tag:
            description: "Tag to create the release for"
            required: true
            default: "v1.0.0"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push new tag
        id: tag
        run: |
          echo "Pushing new tag..."
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}

      - name: Update CHANGELOG
        id: changelog
        uses: ./actions/generate-changelog
        with:
          tag: ${{ inputs.tag }}
          include_invalid_commits: 'true'

      - name: Create Release
        uses: ./actions/create-release
        with:
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ inputs.tag }}