name: Release
run-name: Release - ${{ github.sha }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: 4.0.0

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          makeLatest: true
          name: 4.0.0
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}