name: Release
run-name: Release - ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
        tag:
            description: "Tag to create the release for"
            required: true
            default: "v1.0.0"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push new tag
        id: tag
        run: |
          echo "Pushing new tag..."
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ inputs.tag }}
          includeInvalidCommits: true

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          makeLatest: true
          name: ${{ inputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}