name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      foo:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      bar:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.foo }}
      output2: ${{ steps.step2.outputs.bar }}
    steps:
      - id: step1
        run: echo "foo=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "bar=world" >> $GITHUB_OUTPUT