name: Manual Slack Deployment Notification

on:
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: "Seconds to wait before updating message"
        required: false
        default: "3"

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployment started :eyes:"
            attachments:
              - color: "dbab09"
                fields:
                  - title: "Status"
                    short: true
                    value: "In Progress"

      - name: Countdown until launch
        run: sleep ${{ github.event.inputs.delay_seconds }}

      - name: Update the original message with success
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: "Deployment finished! :rocket:"
            attachments:
              - color: "28a745"
                fields:
                  - title: "Status"
                    short: true
                    value: "Completed"

      - name: Comment in thread
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: |
              ✅ Deployment completed!
              <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
      
