name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack Message 1
        id: send_slack_message_1
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is a test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Send Slack Message 2
        id: send_slack_message_2
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is *another* test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Update Slack Message 1
        uses: ./actions/slack/update-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'This is an updated message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          ts: ${{ steps.send_slack_message_1.outputs.ts }}

      - name: Send Workflow Status Message 1
        id: send_workflow_status_message_1
        uses: ./actions/slack/send-workflow-status-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          status: 'ongoing'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          tag: 'test-${{ github.run_number }}-${{ github.sha }}'
          env: 'prod'

      - name: Send Slack Message 3
        id: send_slack_message_3
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is *the third* test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Update Workflow Status Message 1
        uses: ./actions/slack/update-workflow-status-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          status: 'success'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          ts: ${{ steps.send_workflow_status_message_1.outputs.ts }}
          tag: 'test-${{ github.run_number }}-${{ github.sha }}'
          env: 'prod'

      - name: Send Slack Message 4
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Finished'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          thread_ts: ${{ steps.send_workflow_status_message_1.outputs.ts }}

      - name: Send Workflow Status Message 5
        uses: ./actions/slack/send-workflow-status-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          status: 'ongoing'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          tag: 'test-${{ github.run_number }}-${{ github.sha }}'
          env: 'prod'
          thread_ts: ${{ steps.send_slack_message_3.outputs.ts }}