name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployment started :eyes:"
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "🚀 Deployment Started"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Repository:*\n${{ github.repository }}"
                  - type: mrkdwn
                    text: "*Workflow:*\n${{ github.workflow }}"
                  - type: mrkdwn
                    text: "*Run #:*\n${{ github.run_number }}"
                  - type: mrkdwn
                    text: "*Actor:*\n${{ github.actor }}"
                  - type: mrkdwn
                    text: "*Run URL:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"

      - name: Comment in thread 1
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: ✅ *Deployment completed* - <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>

      - name: Comment in thread 2
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: ✅ *Deployment completed* - <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>

      - name: Comment in thread 3
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: ""
            text: ✅ *Deployment completed* - <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>

      - name: Comment in thread 4
        id: comment_thread_4
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: '✅ *Deployment finished* ✅'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Comment in thread 5
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: '✅ *Deployment finished* ✅'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          thread_ts: "${{ steps.comment_thread_4.outputs.ts }}"