name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack Message 1
        id: send_message_1
        uses: ./actions/slack/text-message/send
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This is a message from the GitHub Actions workflow #1"
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Send Slack Message 2
        id: send_message_2
        uses: ./actions/slack/text-message/send
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This is a message from the GitHub Actions workflow #2"
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Update Slack Message 2
        uses: ./actions/slack/text-message/update
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This was a message from the GitHub Actions workflow #2, now *updated*"
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          ts: ${{ steps.send_message_2.outputs.ts }}

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Send Slack Message 3 on Message 2 Thread
        uses: ./actions/slack/text-message/send
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This is a message from the GitHub Actions workflow #3 in the thread of message #2"
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          thread_ts: ${{ steps.send_message_2.outputs.ts }}

      - name: Send Deployment Status Message 1
        id: send_deployment_status_1
        uses: ./actions/slack/payload-templated-message/send-deployment-status
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          emoji: ':arrows_counterclockwise:'
          env: 'prod'
          tag: 'tag-${{ github.sha }}'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack Message 5 on Deployment Status Message 1 Thread
        uses: ./actions/slack/text-message/send
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This is a message from the GitHub Actions workflow #5 in the thread of deployment status message #1"
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          thread_ts: ${{ steps.send_deployment_status_1.outputs.ts }}

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Update Deployment Status Message 1
        uses: ./actions/slack/payload-templated-message/update-deployment-status
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          emoji: ':x:'
          env: 'prod'
          tag: 'tag-${{ github.sha }}'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          ts: ${{ steps.send_deployment_status_1.outputs.ts }}

      - name: Send Slack Message 6 on Deployment Status Message 1 Thread
        uses: ./actions/slack/text-message/send
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "This is a message from the GitHub Actions workflow #6 in the thread of deployment status message #1"
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          thread_ts: ${{ steps.send_deployment_status_1.outputs.ts }}

      - name: Update Deployment Status Message 1
        uses: ./actions/slack/payload-templated-message/update-deployment-status
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          emoji: ':white_check_mark:'
          env: 'prod'
          tag: 'tag-${{ github.sha }}'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          ts: ${{ steps.send_deployment_status_1.outputs.ts }}