name: Manual Slack Deployment Notification

on:
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: "Seconds to wait before updating message"
        required: false
        default: "3"

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployment started :eyes:"
            attachments:
              - color: "dbab09"
                fields:
                  - title: "Status"
                    short: true
                    value: "In Progress"
            blocks:
                - type: header
                    text:
                    type: plain_text
                    text: ":rocket: Deployment Notification"
                - type: section
                    text:
                    type: mrkdwn
                    text: "Deployment initiated for `${{ github.repository }}`"
                - type: section
                    fields:
                      - type: mrkdwn
                        text: "*Workflow:*\n`${{ github.workflow }}`"
                      - type: mrkdwn
                        text: "*Run #:*\n`${{ github.run_number }}`"
                      - type: mrkdwn
                        text: "*Repository:*\n`${{ github.repository }}`"
            

      - name: Comment in thread
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            thread_ts: "${{ steps.launch_sequence.outputs.ts }}"
            text: |
              ✅ Deployment completed!
              <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
      
