name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack Message - without Blocks
        id: send_slack_message_without_blocks
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is a test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Send Workflow Status Message
        id: send_workflow_status_message
        uses: ./actions/slack/send-workflow-status-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          tag: "tag-${{ github.sha }}"
          env: 'qa'
          status: 'ongoing'

      - name: Sleep 3 seconds
        run: sleep 3

      - name: Update Workflow Status Message
        uses: ./actions/slack/update-workflow-status-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          tag: "tag-${{ github.sha }}"
          env: 'qa'
          status: 'success'
          ts: ${{ steps.send_workflow_status_message.outputs.ts }}