name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack Message - without Blocks
        id: send_slack_message_without_blocks
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is a test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack Message - with Blocks
        id: send_slack_message_with_blocks
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          blocks: |
            - type: header
              text:
                type: plain_text
                text: "${{ github.workflow }} #${{ github.run_number }} ${{ steps.get_status_emoji.outputs.emoji }}"
                emoji: true
            - type: divider
            - type: context
              elements:
                - type: mrkdwn
                  text: "• *Repository:* `${{ github.repository }}`"
            - type: context
              elements:
                - type: mrkdwn
                  text: "• *Branch:* `${{ github.ref_name }}`"
            - type: context
              elements:
                - type: mrkdwn
                  text: "• *Environment:* `qa`"
            - type: context
              elements:
                - type: mrkdwn
                  text: "• *Tag:* `tag-${{ github.sha }}`"
            - type: context
              elements:
                - type: mrkdwn
                  text: "• *Run by:* `@${{ github.actor }}`"
            - type: divider
            - type: section
              fields:
                - type: mrkdwn
                  text: ":copyright: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
                - type: mrkdwn
                  text: ":page_facing_up: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>"

