name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack message with blocks
        id: send_slack_message_text
        uses: ./actions/slack/send-message-with-blocks
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: "Deployment to prod completed successfully!"
          tag: 'berger'
          env: 'qa'