name: Manual Slack Deployment Notification

on:
  workflow_dispatch:

jobs:
  notify-deployment:
    name: Notify Slack of deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Slack Message - without Blocks
        id: send_slack_message_without_blocks
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: 'Hello world! This is a test message from _GitHub Actions_.'
          token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack Message - with Blocks
        id: send_slack_message_with_blocks
        uses: ./actions/slack/send-message
        with:
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          text: ''
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          blocks: >
            [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Deploy succeeded*"
                }
              }
            ]
