name: Template CI Workflow
description: Simple template CI workflow with echo steps
on:
  workflow_call:

jobs:
  echo-template:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from template
        run: echo "👋 Hello from template workflow!"
