name: Test Validate Multiple Inputs

on:
  workflow_dispatch:

env:
  # Set example input values; you can leave one blank to test validation
  YAML_FILE_PATH: './app/config.yaml'
  YAML_FIELD_PATH: ''         # ← Leave empty to simulate failure
  NEW_YAML_FIELD_VALUE: ''
  EMOJI_2: ':rocket:'
  EMOJI_1: ''

jobs:
  test_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run input validation
        uses: ./actions/validation/validate-multiple-inputs
        with:
          list_of_inputs: |
            yaml_file_path=${{ env.YAML_FILE_PATH }}
            yaml_field_path=${{ env.YAML_FIELD_PATH }}
            new_yaml_field_value=${{ env.NEW_YAML_FIELD_VALUE }}
            emoji_1=${{ env.EMOJI_1 }}
            emoji_2=${{ env.EMOJI_2 }}