name: Validate Inputs Matrix

on:
  workflow_call:

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input_name: [ "repository", "ref", "token" ]
    steps:
    - name: Validate all inputs
      uses: ./actions/validation/validate-multiple-inputs
      env:
        INPUTS: |
          foo="FOO"
          bar="BAR"
          buzz=""
          

