name: Validate Inputs Matrix

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input_name: [ "repository", "ref", "token" ]
    steps:
      - name: Validate input '${{ matrix.input_name }}'
        uses: ./actions/validate-required-input
        with:
          input_name: ${{ matrix.input_name }}
          input_value: ${{ inputs[matrix.input_name] }}
